### ISSUE TITLE
[QUESTION] Can this be integrated with Roblox Studio?

### ISSUE THREAD

**Issue by Liam31** [JiveOff/roPresence#107]
I'd like to use this for studio to what game I'm editing if I'm working in a script or the workspace. I'm not experienced with JS so I might not be able to fully do this, but I'm curious if it's possible.

**Comment by Liam31** [comment]
Also, I couldn't properly at the question tag, so I apologize.

**Comment by JiveOff** [comment]
We can't detect if you are in a script or in the workspace without a Studio plugin and I'm not even sure if the plugins can communicate with local express servers. I will take a look, thanks for the suggestion!
