### ISSUE TITLE
[BUG] Can't connect

### ISSUE THREAD

**Issue by foxt** [JiveOff/roPresence#12]
**Describe the bug**
Won't connect to Discord

**To Reproduce**
Run the thing.

**Expected behavior**
It connects and works.

**Screenshots**
![image](https://user-images.githubusercontent.com/12257112/63966081-6af52f00-ca92-11e9-81ff-186526f71f33.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version: roPresence v1.0.4

**Additional context**
other rich presence apps work fine 🤷‍♂

**Comment by JiveOff** [comment]
Hello there,Are you running Discord on your desktop? From what I can see, discord-rpc can't find an IPC server. Le 29 août 2019 8:24 PM, Leo Nesfield <notifications@github.com> a écrit :Assigned #12 to @JiveOff.

**Comment by foxt** [comment]
Yes. Other rich presences work fine

**Comment by JiveOff** [comment]
Very weird. Did you try running the binary or re install the packages?

**Comment by foxt** [comment]
@JiveOff git cloned the repo

**Comment by JiveOff** [comment]
Try getting an older version and tell me if it works. You can find them on the releases tab.

**Comment by foxt** [comment]
@JiveOff actually no, just checked i downloaded 1.0.4

**Comment by Monkey8729** [comment]
Hello, 
Versions below  **1.0.3.1** Will work with Mac OS. I have tried using 1.0.4 as well and I have not been able to get it to work with Mac OS or Linux.

**Comment by sasial-dev** [comment]
Basically.
**Binary's __DO NOT__ work for MacOs**
