### ISSUE TITLE
How to shut RoPresence off

### ISSUE THREAD

**Issue by EthanicMan** [JiveOff/roPresence#120]
RoPresence keeps displaying on Discord even after I close my browser. How do I manually turn it off, or is this a bug as well?
![image](https://user-images.githubusercontent.com/72815967/102145531-a13ff480-3e24-11eb-8087-42728427c46e.png)

**Comment by JiveOff** [comment]
You can't run the presence on the browser, you probably have Discord installed on your computer.

You can shutdown the presence by going on your tray menu and clicking "Quit".
