### ISSUE TITLE
Change 'ROBLOX' to 'Roblox'

### ISSUE THREAD

**Issue by chaugen1** [JiveOff/roPresence#14]
**Is your feature request related to a problem? Please describe.**
Roblox has changed their brand name from 'ROBLOX' to 'Roblox' almost 2 years ago and it would fit better if it was changed.

**Describe the solution you'd like**
Instead of it showing 'Playing ROBLOX' it should display 'Playing Roblox'

**Comment by JiveOff** [comment]
Fixed.
