### ISSUE TITLE
[BUG] Newer Versions of roPresence, do NOT work with Mac. 

### ISSUE THREAD

**Issue by GameAddict7** [JiveOff/roPresence#18]
Bug Issue: roPresence only works on Mac with version 1.0.3.1 and lower. When trying to start roPresence on later versions beyond 1.0.3.1, this error message is recieved:
Failed to connect to Discord!
Make sure that Discord has been launched and that you're logged in, then launch roPresence again.

To reproduce the behavior, install a later version of 1.0.3.1 using MacOs and type the following command:
npm start

Expected Behavior: Expected Behavior is that roPresence will successfully log in to the user's account:
RPC: Logged in as GameAddict_7 (406937395737395200).
roPresence Loaded - Glad to see you, GameAddict_7! Your presence will be updated once you interact with ROBLOX.
Presence API: Your Discord presence will now be updated every 15 seconds with the GameAddict_7 ROBLOX Account.
If you unverify, roPresence will stop showing the Discord Presence and ask you to verify yourself again.

To keep the Discord Presence, DO NOT close this window. You can close it when you will be done.

Desktop: 
iMac (Retina 4K, 21.5-inch, 2017)
MacOs Mohave 1.14.6

-Credit to Sasial for helping me on this issue.

**Comment by sasial-dev** [comment]
Working on a fix for this.

**Comment by sasial-dev** [comment]
Was helping @GameAddict7 set roPresence up and we found the only way to make it work was to use 1.0.3.1 and below.

**Comment by GameAddict7** [comment]
Ok thanks!

**Comment by sasial-roblox** [comment]
#21
