### ISSUE TITLE
[BUG] An roPresence API Error

### ISSUE THREAD

**Issue by karimrir1** [JiveOff/roPresence#26]
*********************************************************************************************
 *** roPresence v1.0.5 Launched: Tue Dec 10 2019 10:45:04 GMT+0300 (Arabian Standard Time) ***
 *********************************************************************************************

 * Non-terminal slave process launched.
RPC: Attempting to login through IPC.
roPresence Express kill server online.
RPC: Logged in as KarimrirPlayzDev (492015969728724992).
roPresence API Error - roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
Please restart the presence.
roPresence: Stopping. Exiting cmd in 10 seconds.

**Comment by JiveOff** [comment]
Fixed.
