### ISSUE TITLE
[BUG] API Error 

### ISSUE THREAD

**Issue by Randomspy1** [JiveOff/roPresence#27]
********************************************************************************************************
 *** roPresence v1.0.4 Launched: Fri Dec 13 2019 17:40:35 GMT+1100 (Australian Eastern Daylight Time) ***
 ********************************************************************************************************

roPresence Express kill server online.
 * Non-terminal slave process launched.
RPC: Attempting to login through IPC.
RPC: Logged in as _kyse_ (406676381699801088).
roPresence API Error - roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
Please restart the presence.
roPresence: Stopping. Exiting cmd in 10 seconds.

**Comment by JiveOff** [comment]
Fixed.
