### ISSUE TITLE
[BUG] It's showing my old username

### ISSUE THREAD

**Issue by Rawblocky** [JiveOff/roPresence#3]
**Describe the bug**
It is showing my old username.

**To Reproduce**
Have an old username and open "Windows_Presence.bat"

**Expected behavior**
It should say "RPC: Logged in as <current username>" then the line under it will be "roPresence Loaded - Glad to see you, <old username>!"

**Screenshots**
![image](https://user-images.githubusercontent.com/26015280/61412892-f2019580-a89e-11e9-918e-c072121d998a.png)

**Comment by ghost** [comment]
Reverify here https://verify.eryn.io/

**Comment by JiveOff** [comment]
You need to reverify. The data is provided from Eryn's website.
