### ISSUE TITLE
[BUG] Connection Refused on Startup

### ISSUE THREAD

**Issue by MoonBarc** [JiveOff/roPresence#38]
**Describe the bug**
When running the binary, I am greeted with a lovely `connection refused`. The site that is sending connection refused is `http://vps1.jiveoff.fr:3000/presences/102697445`. Is your server down?

**To Reproduce**
1. Run the binary.

**Expected behavior**
I expected it to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: windows 10 (idk build sorry)

**Comment by JiveOff** [comment]
Hello there,

I will look into it now.

**Comment by JiveOff** [comment]
Should be resolved now, thanks for the report!
