### ISSUE TITLE
[BUG] API Error

### ISSUE THREAD

**Issue by OfficialCRUGG** [JiveOff/roPresence#44]
**Describe the bug**
When trying to launch, it gives me an API Error and exists after 10 Seconds.

**To Reproduce**
1. Start roPresence

**Expected behavior**
It should work and do what the Software is made for, show the the Rich Presence.

**Screenshots**
![image](https://user-images.githubusercontent.com/25248999/85428383-677ce800-b57d-11ea-872d-e5dbefd8125c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 (if this means the OS Version; if it's about the roPresence Version: 2.0.0)

**Comment by JiveOff** [comment]
Did a restart fix your issue? Are you manipulating your firewall?

**Comment by OfficialCRUGG** [comment]
> Did a restart fix your issue?

Didn't try yet and I prefer not to, if the Issue can be fixed otherwise, since restarting takes ages for me

> Are you manipulating your firewall?

No


If it's an external API, can you give an example Endpoint so I can try if I can access it outside of roPresence?

**Comment by MattGeek** [comment]
Do you have the "who can join me in game?" setting to at least "Friends and Users I Follow"?
It is required for roPresence_bot to see your activity on Roblox.

**Comment by OfficialCRUGG** [comment]
Yes, that is definitely Public.

**Comment by MattGeek** [comment]
Well, I was receiving that error because my privacy settings weren't correct

**Comment by OfficialCRUGG** [comment]
The only thing is that I have set it so also Followers of me can join but that shouldn't be a difference. Otherwise, I'd probably guess there is actually a problem with either the API or the communication between my client and the API.

**Comment by sasial-dev** [comment]
@OfficialCRUGG, if you can restart roPresence that might do it.
Other than that, could've just been a Roblox API problem at the time.
![image](https://user-images.githubusercontent.com/44125644/85488767-339fd200-b612-11ea-9790-8d616f9eec5e.png)

**Comment by OfficialCRUGG** [comment]
> if you can restart roPresence that might do it.

I already did that multiple times.

And it is still not working, even after a PC Restart.

**Comment by StromcekDavid** [comment]
Also got this error.

OS: Windows 10 Professional
Version: 1909, build 18363.900
roPresence version: 2.1.0

**Comment by OfficialCRUGG** [comment]
Yesterday evening it started to work again. Seems to have been a temporary Issue, however I don't exactly know what caused it.
