### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by Underpants-dev** [JiveOff/roPresence#46]
![image](https://user-images.githubusercontent.com/52192223/85502310-ad30c380-b604-11ea-987d-2cd3989feb96.png)

i cannot open the RoPresence setup file

**Comment by sasial-dev** [comment]
Electron and Antivirus are not friends.
Change your settings to allow you to bypass SmartScreen.
Let me know if you need a hand showing you how to.
(My discord is Sasial#9375) 
@sweetchikoo2403
