### ISSUE TITLE
Game name not showing[BUG]

### ISSUE THREAD

**Issue by ghost** [JiveOff/roPresence#47]
**Describe the bug**
I have followed the but on roblox and it won't display my game presence on discord, i have tried reinstalling it, running it as administrator and re verifying it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the app
2. Join a game
3. The rich presence won't appear

**Expected behavior**
Discord displays activity.

**Screenshots**
![image](https://user-images.githubusercontent.com/11794116/85617901-e2b2cc80-b657-11ea-86c6-7d7948257b4b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Windows 10 pro 1909

**Additional context**

**Comment by JiveOff** [comment]
Hello,

Please read the README.md entirely next time, your issue is adressed here: https://github.com/JiveOff/roPresence#making-the-game-name-show
