### ISSUE TITLE
[BUG] Remote API Problem for Windows Presence

### ISSUE THREAD

**Issue by Jaguar-515** [JiveOff/roPresence#5]
**Describe the bug**
In the screenshot below, roPresence says that there is a Remote API problem.

**To Reproduce**
1. Go to the roPresence folder wherever you installed it
2. Click on 'Windows_Presence'
3. See error

**Expected behavior**
I expected roPresence to work normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/48777426/61551043-f9dd4900-aa08-11e9-89f1-d48e334e194f.png)

**Desktop**
 - OS: Windows 10
 - Version: 10.0.17763 Build 17763

**Comment by ghost** [comment]
API is probably down

**Comment by Jaguar-515** [comment]
When did the API go down, if it did go down?

**Comment by ghost** [comment]
I don't know when but the API is returning "{"request":{"status":"error","error":"API is disconnected from ROBLOX."}}" so I don't know.

**Comment by JiveOff** [comment]
API fixed and restarted. You can re use it. ^^
