### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by arandomjon** [JiveOff/roPresence#51]
Got stuck here a few times. I don't think it's me. I've restarted the thing a few times

> roPresence: Stopping. Exiting cmd in 5 seconds.
> RPC: Attempting to login through IPC.
> RPC: Logged in as SPCSterling (442416217853132812).
> FetchError: request to http://vps1.jiveoff.fr:3000/presences/165001466 failed, reason: socket hang up
> roPresence: Stopping. Exiting cmd in 5 seconds.
> Socket Client: Starting.
> roPresence API Error: roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
> Please restart the presence.
> Socket Client: Connected to socket, authenticating.
> Socket Client: Authenticated to socket, ready.
> RPC: Attempting to login through IPC.
> RPC: Logged in as SPCSterling (442416217853132812).

**Comment by TrackOne62817** [comment]
Yep, it keeps happening to me.

**Comment by JiveOff** [comment]
I plan to rewrite roPresence to completely annihilate this error from Windows by using the registry cookies.

I will publish a beta very soon.

**Comment by JiveOff** [comment]
This issue has been addressed in our last Windows release.
Closing.
