### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by josefalhashimi** [JiveOff/roPresence#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When i open it keeps saying ran into an error and had to stop
**Screenshots** 
![error msg)](https://user-images.githubusercontent.com/67482606/86480343-24293300-bd4e-11ea-9bf2-76bb0e00931d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS] windows
 - Version [e.g. 22] the newst version

**Additional context**

**Comment by JiveOff** [comment]
Download the latest release and re-open an issue that is correctly formatted if it happens again.
