### ISSUE TITLE
[SUGGESTION] Startup with Windows

### ISSUE THREAD

**Issue by redJuli21** [JiveOff/roPresence#58]
**Is your feature request related to a problem? Please describe.**
No, It's just a suggestion that will make the experience easier and better.

**Describe the solution you'd like**
That app starts when I log into windows, I know I can use Task Scheduler but other users may not know.

**Describe alternatives you've considered**
Putting the app in Task Scheduler to run when I log in.

**Additional context**
App should appear in this menu:
![image](https://user-images.githubusercontent.com/56458705/87449336-4dea2180-c5ba-11ea-81b9-deac24558e62.png)

**Comment by JiveOff** [comment]
I totally agree with you on this one. I will look into that and keep you updated.

**Comment by JiveOff** [comment]
I will release the executable when the build is done on my side. Thanks for the suggestion!

**Comment by JiveOff** [comment]
@TotallyNotInUse https://github.com/JiveOff/roPresence/releases/tag/2.1.2

You can now download the new release. ^^

**Comment by redJuli21** [comment]
Thank you!
