### ISSUE TITLE
roPresence won't work

### ISSUE THREAD

**Issue by joegravil** [JiveOff/roPresence#67]
I have followed your guide and I still can't get ropresence to work and I was wondering if you could let me know what the full setup process is so I can see if im missing anything

**Comment by JiveOff** [comment]
You just have to download the Setup.exe present in the releases...

**Comment by ghost** [comment]
I had the same problem just wait for a couple maybe a day

**Comment by JiveOff** [comment]
Please re-open an issue if you are still experiencing issues.
