### ISSUE TITLE
[BUG] Microsoft Edge blocks download

### ISSUE THREAD

**Issue by QkeleQ10** [JiveOff/roPresence#76]
**Describe the bug**
The new Microsoft Edge (which runs on Chromium) blocks the download because "it could harm my device". 

**To Reproduce**
1. Open/install the new Microsoft Edge
2. Download Setup.exe
3. See Edge blocks the download

**To Fix**
You can ask Microsoft to remove this by downloading Setup.exe, clicking the three dots next to the error when finished, _Report this file as safe_ and selecting something along the lines of _I'm the owner of the website and I want to report an incorrect warning_.

**Screenshots**
Click this button... ![image](https://user-images.githubusercontent.com/55982900/89100928-b3803f80-d3fb-11ea-9e46-da1868e475e7.png)
...to report an incorrect warning ![image](https://user-images.githubusercontent.com/55982900/89100985-4e791980-d3fc-11ea-8180-a4dee4821267.png) (same in English/French)

**Comment by StapledRubber** [comment]
I believe that there is no way of getting around Microsoft Edge's file upload scan, you may have to use a browser like Firefox that does not do this.

**Comment by JiveOff** [comment]
Since it is not an app bug, I will close this issue. I can't afford a licence to sign an open source executable.
