### ISSUE TITLE
[BUG] Windows Powershell Terminal not opening up

### ISSUE THREAD

**Issue by StapledRubber** [JiveOff/roPresence#77]
Whenever I try to create a Windows Powershell Terminal on a blank part of the roPresence folder, it never works.

1. Go into the roPresence folder.
2. Hold Ctrl+Caps then right click.
3. Nothing happens for me.

 - OS: Windows 10 Home Edition (Laptop)
 - Version: Newest Release

**Comment by JiveOff** [comment]
You should use the binaries instead of the source code.

**Comment by StapledRubber** [comment]
Ok, thanks.
