### ISSUE TITLE
[SUGGESTION] Change the discord application name

### ISSUE THREAD

**Issue by MirayXS** [JiveOff/roPresence#78]
**Is your feature request related to a problem? Please describe.**
Discord's can auto-detect when someone is playing a game, and set a RPC. Roblox has the name of " ROBLOX "

**Describe the solution you'd like**
The roPresence application name is " Roblox ", but to make it more realistic, you could change the app name to " ROBLOX ". 

**Additional context**
you can do it in less than a minute, if you do, thanks 👍 

* this is only a discord application change

**Comment by JiveOff** [comment]
The thing is that, legally, it is Roblox and not ROBLOX. I understand your point and it was like that at the beginning.

**Comment by JiveOff** [comment]
For the sake of realism, I will rename it. ;)
