### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JaxonPlays** [JiveOff/roPresence#9]
I have a quick question. Is there a way to start "roPresence" when you start your computer?

**Comment by JiveOff** [comment]
Hello there,
This issue is not a bug but an enhancement. You can have a quick look on Google for a startup script for your OS.
A BetterDiscord version will be available soon.

**Comment by foxt** [comment]
use pm2 for linux/macos, and just put a lnk in your startup folder on wiindows
